name: my_book_store
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  device_preview: ^1.1.0
  google_fonts: ^5.1.0
  get: ^4.6.5
  flutter_svg: ^2.0.7
  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  path_provider: ^2.1.0
  shared_preferences: ^2.2.0
  syncfusion_flutter_pdfviewer: ^22.2.8
  flutter_screenutil: ^5.8.4
  shimmer: ^3.0.0
  yako_theme_switch: ^1.0.0+1
  provider: ^6.0.5
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  freezed: ^2.4.2
  firebase_core: ^2.15.1
  cloud_firestore:
  firebase_storage:
  firebase_database:
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  #  flutter pub add freezed_annotation
  #  flutter pub add --dev build_runner
  #  flutter pub add --dev freezed

  #  dart run build_runner watch --delete-conflicting-outputs
