name: my_book_store
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  device_preview: ^1.1.0
  google_fonts: ^5.1.0
  get: ^4.6.5
  flutter_svg: ^2.0.7
  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  path_provider: ^2.1.0
  shimmer: ^3.0.0
  shared_preferences: ^2.2.0
  syncfusion_flutter_pdfviewer: ^22.2.8
  permission_handler: ^10.4.3
  flutter_screenutil: ^5.8.4
  yako_theme_switch: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
